title: "The title of your A short description of your site's purpose"
description: "A short description of your site's purpose"
logo: /assests/img/logo.png
show_downloads: true
google_analytics: 
theme: jekyll-theme-minimal